### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SRSFFGAMING** [ThatsLiamS/Coin-Flipper#26]
### Description

Without buying we can use party poppers for unlimited time pls fix that , some issues in badges i can't claim badges and have gaved like powers in shop by buying a item it will give some extra lucky chance but that not working so fix it mainluy

### Steps To Reproduce

Explained all in description 

### Expected behavior

Need to be fixed as soon as possible 

### Discord Version

Latest

### Shard Id

Idk

**Comment by ThatsLiamS** [comment]
Greetings, kindly ensure that all the fields are filled out accurately and comprehensively, providing as much relevant information as possible for each issue. The reason for the inclusion of these questions is to facilitate a thorough and effective investigation of the matter at hand.

### Overview of the form
- **Steps to Reproduce** means explain the steps, commands, arguments you provided when you encountered each error or bug. The preview text shows an outline of how it should be answered. 

- **Expected Behaviour**. What is the command suppose to do and what did it do instead? At what stage did you receive the incorrect behaviour. 

- **Versions**. Simply run the `/about` command to get the Shard ID and go into the client settings to view the Discord Version. Simply stating "latest" doesn't explain anything - how do you know it is the latest, what if a new version came out afterwards etc etc.

- **Relevant Assets/Logs**. Show us evidence, screenshots, that there is a problem.
